// Code generated by protoc-gen-go. DO NOT EDIT.
// source: turn2.proto

package turn2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type IntoData struct {
	Data                 []*IntoData_Record `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	PublicPoker          []int32            `protobuf:"varint,2,rep,packed,name=PublicPoker,proto3" json:"PublicPoker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *IntoData) Reset()         { *m = IntoData{} }
func (m *IntoData) String() string { return proto.CompactTextString(m) }
func (*IntoData) ProtoMessage()    {}
func (*IntoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_86771477222ac627, []int{0}
}

func (m *IntoData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntoData.Unmarshal(m, b)
}
func (m *IntoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntoData.Marshal(b, m, deterministic)
}
func (m *IntoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntoData.Merge(m, src)
}
func (m *IntoData) XXX_Size() int {
	return xxx_messageInfo_IntoData.Size(m)
}
func (m *IntoData) XXX_DiscardUnknown() {
	xxx_messageInfo_IntoData.DiscardUnknown(m)
}

var xxx_messageInfo_IntoData proto.InternalMessageInfo

func (m *IntoData) GetData() []*IntoData_Record {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *IntoData) GetPublicPoker() []int32 {
	if m != nil {
		return m.PublicPoker
	}
	return nil
}

type IntoData_Record struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Pokers               []int32  `protobuf:"varint,2,rep,packed,name=Pokers,proto3" json:"Pokers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntoData_Record) Reset()         { *m = IntoData_Record{} }
func (m *IntoData_Record) String() string { return proto.CompactTextString(m) }
func (*IntoData_Record) ProtoMessage()    {}
func (*IntoData_Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_86771477222ac627, []int{0, 0}
}

func (m *IntoData_Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntoData_Record.Unmarshal(m, b)
}
func (m *IntoData_Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntoData_Record.Marshal(b, m, deterministic)
}
func (m *IntoData_Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntoData_Record.Merge(m, src)
}
func (m *IntoData_Record) XXX_Size() int {
	return xxx_messageInfo_IntoData_Record.Size(m)
}
func (m *IntoData_Record) XXX_DiscardUnknown() {
	xxx_messageInfo_IntoData_Record.DiscardUnknown(m)
}

var xxx_messageInfo_IntoData_Record proto.InternalMessageInfo

func (m *IntoData_Record) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IntoData_Record) GetPokers() []int32 {
	if m != nil {
		return m.Pokers
	}
	return nil
}

// The response message containing the greetings
type OutData struct {
	OverCardNumber       int32    `protobuf:"varint,1,opt,name=OverCardNumber,proto3" json:"OverCardNumber,omitempty"`
	LeaderId             string   `protobuf:"bytes,2,opt,name=LeaderId,proto3" json:"LeaderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutData) Reset()         { *m = OutData{} }
func (m *OutData) String() string { return proto.CompactTextString(m) }
func (*OutData) ProtoMessage()    {}
func (*OutData) Descriptor() ([]byte, []int) {
	return fileDescriptor_86771477222ac627, []int{1}
}

func (m *OutData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutData.Unmarshal(m, b)
}
func (m *OutData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutData.Marshal(b, m, deterministic)
}
func (m *OutData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutData.Merge(m, src)
}
func (m *OutData) XXX_Size() int {
	return xxx_messageInfo_OutData.Size(m)
}
func (m *OutData) XXX_DiscardUnknown() {
	xxx_messageInfo_OutData.DiscardUnknown(m)
}

var xxx_messageInfo_OutData proto.InternalMessageInfo

func (m *OutData) GetOverCardNumber() int32 {
	if m != nil {
		return m.OverCardNumber
	}
	return 0
}

func (m *OutData) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func init() {
	proto.RegisterType((*IntoData)(nil), "turn2.IntoData")
	proto.RegisterType((*IntoData_Record)(nil), "turn2.IntoData.Record")
	proto.RegisterType((*OutData)(nil), "turn2.OutData")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Turn2Client is the client API for Turn2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Turn2Client interface {
	// Sends a greeting
	CalculatorFlop(ctx context.Context, in *IntoData, opts ...grpc.CallOption) (*OutData, error)
}

type turn2Client struct {
	cc *grpc.ClientConn
}

func NewTurn2Client(cc *grpc.ClientConn) Turn2Client {
	return &turn2Client{cc}
}

func (c *turn2Client) CalculatorFlop(ctx context.Context, in *IntoData, opts ...grpc.CallOption) (*OutData, error) {
	out := new(OutData)
	err := c.cc.Invoke(ctx, "/turn2.Turn2/CalculatorFlop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Turn2Server is the server API for Turn2 service.
type Turn2Server interface {
	// Sends a greeting
	CalculatorFlop(context.Context, *IntoData) (*OutData, error)
}

func RegisterTurn2Server(s *grpc.Server, srv Turn2Server) {
	s.RegisterService(&_Turn2_serviceDesc, srv)
}

func _Turn2_CalculatorFlop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntoData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Turn2Server).CalculatorFlop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turn2.Turn2/CalculatorFlop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Turn2Server).CalculatorFlop(ctx, req.(*IntoData))
	}
	return interceptor(ctx, in, info, handler)
}

var _Turn2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "turn2.Turn2",
	HandlerType: (*Turn2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatorFlop",
			Handler:    _Turn2_CalculatorFlop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "turn2.proto",
}

func init() { proto.RegisterFile("turn2.proto", fileDescriptor_86771477222ac627) }

var fileDescriptor_86771477222ac627 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x35, 0x59, 0x5b, 0xd7, 0x29, 0x54, 0x98, 0xc3, 0x52, 0x7a, 0x2a, 0x3d, 0x48, 0xf1, 0x50,
	0xa4, 0x7b, 0xf5, 0xe4, 0x8a, 0x10, 0x50, 0xb7, 0x04, 0x7f, 0x20, 0x6d, 0x72, 0x10, 0xe3, 0x66,
	0x19, 0x13, 0x3f, 0xc2, 0xaf, 0x96, 0xcd, 0x46, 0x91, 0x3d, 0x0d, 0xef, 0xcd, 0x7b, 0xf3, 0x78,
	0x03, 0x85, 0x0f, 0xb4, 0x1b, 0xfa, 0x3d, 0x39, 0xef, 0x30, 0x8b, 0xa0, 0xfd, 0x66, 0xb0, 0x14,
	0x3b, 0xef, 0x1e, 0x94, 0x57, 0x78, 0x03, 0xe7, 0x87, 0x59, 0xb1, 0x66, 0xd1, 0x15, 0xc3, 0xaa,
	0x3f, 0xea, 0x7f, 0xd7, 0xbd, 0x34, 0xb3, 0x23, 0x2d, 0xa3, 0x06, 0x1b, 0x28, 0xc6, 0x30, 0xd9,
	0xb7, 0x79, 0x74, 0xef, 0x86, 0x2a, 0xde, 0x2c, 0xba, 0x4c, 0xfe, 0xa7, 0xea, 0x5b, 0xc8, 0x8f,
	0x0e, 0x2c, 0x81, 0x0b, 0x5d, 0xb1, 0x86, 0x75, 0x97, 0x92, 0x0b, 0x8d, 0x2b, 0xc8, 0xa3, 0xe4,
	0x33, 0xd9, 0x12, 0x6a, 0x9f, 0xe1, 0x62, 0x1b, 0x7c, 0x3c, 0x7f, 0x0d, 0xe5, 0xf6, 0xcb, 0xd0,
	0x46, 0x91, 0x7e, 0x09, 0x1f, 0x93, 0xa1, 0x68, 0xcf, 0xe4, 0x09, 0x8b, 0x35, 0x2c, 0x9f, 0x8c,
	0xd2, 0x86, 0x84, 0xae, 0x78, 0x0c, 0xf8, 0xc3, 0xc3, 0x1d, 0x64, 0xaf, 0x87, 0x06, 0xb8, 0x86,
	0x72, 0xa3, 0xec, 0x1c, 0xac, 0xf2, 0x8e, 0x1e, 0xad, 0xdb, 0xe3, 0xd5, 0x49, 0xb7, 0xba, 0x4c,
	0x44, 0xca, 0x6f, 0xcf, 0xee, 0xf9, 0xc8, 0xa6, 0x3c, 0xfe, 0x6a, 0xfd, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x19, 0xd5, 0x3a, 0xb3, 0x3a, 0x01, 0x00, 0x00,
}
